-- ConectaCup - Modulo interno de Solicitacao de Frete
-- Internaliza os fluxos nacionais e internacionais que antes viviam em
-- Apps Script/Google Sheets, mantendo auditoria, anexos e historico.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.freight_requests (
  id uuid primary key default gen_random_uuid(),
  protocol bigint generated by default as identity unique,
  freight_type text not null default 'nacional',
  status text not null default 'Pendente',

  setor_id uuid references public.setor(id) on delete set null,
  setor text,
  projeto_id uuid references public.projeto(id) on delete set null,
  projeto text,
  projeto_descricao text,

  prazo_entrega timestamptz,
  solicitante_nome text,
  responsavel_entrega text,
  item_descricao text,
  responsavel_local text,
  endereco_retirada text,
  endereco_entrega text,
  pagamento text,
  observacoes text,
  fotos_produto_urls text[] not null default '{}',

  motorista text,
  veiculo text,
  placa text,
  agendamento_at timestamptz,
  observacoes_logistica text,
  foto_entrega_urls text[] not null default '{}',

  necessidade text,
  definitiva_temporaria text,
  observacoes_necessidade text,
  empresa_remetente text,
  endereco_origem text,
  endereco_coleta_origem text,
  nome_contato_origem text,
  email_contato_origem text,
  telefone_contato_origem text,
  empresa_destinatario text,
  endereco_destino text,
  endereco_entrega_destino text,
  nome_contato_destino text,
  email_contato_destino text,
  telefone_contato_destino text,
  prazo_desejado date,
  tipo_frete text,
  modalidade_frete text,
  necessita_seguro text,
  observacoes_finais text,
  empresa_solicitante text,
  cnpj text,
  telefone_solicitante text,
  email_solicitante text,
  responsavel_custos text,
  payload_original jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_by_email text
);

-- Compatibilidade: o projeto ja possui uma freight_requests simples
-- usada por prototipos anteriores. Se ela existir, evoluimos a tabela
-- adicionando as colunas do modulo interno sem apagar dados existentes.
alter table public.freight_requests drop constraint if exists freight_requests_status_check;
alter table public.freight_requests drop constraint if exists freight_requests_priority_check;

alter table public.freight_requests add column if not exists protocol bigint generated by default as identity;
alter table public.freight_requests add column if not exists freight_type text not null default 'nacional';
alter table public.freight_requests add column if not exists setor_id uuid references public.setor(id) on delete set null;
alter table public.freight_requests add column if not exists setor text;
alter table public.freight_requests add column if not exists projeto_id uuid references public.projeto(id) on delete set null;
alter table public.freight_requests add column if not exists projeto text;
alter table public.freight_requests add column if not exists projeto_descricao text;
alter table public.freight_requests add column if not exists prazo_entrega timestamptz;
alter table public.freight_requests add column if not exists solicitante_nome text;
alter table public.freight_requests add column if not exists responsavel_entrega text;
alter table public.freight_requests add column if not exists item_descricao text;
alter table public.freight_requests add column if not exists responsavel_local text;
alter table public.freight_requests add column if not exists endereco_retirada text;
alter table public.freight_requests add column if not exists endereco_entrega text;
alter table public.freight_requests add column if not exists pagamento text;
alter table public.freight_requests add column if not exists observacoes text;
alter table public.freight_requests add column if not exists fotos_produto_urls text[] not null default '{}';
alter table public.freight_requests add column if not exists motorista text;
alter table public.freight_requests add column if not exists veiculo text;
alter table public.freight_requests add column if not exists placa text;
alter table public.freight_requests add column if not exists agendamento_at timestamptz;
alter table public.freight_requests add column if not exists observacoes_logistica text;
alter table public.freight_requests add column if not exists foto_entrega_urls text[] not null default '{}';
alter table public.freight_requests add column if not exists necessidade text;
alter table public.freight_requests add column if not exists definitiva_temporaria text;
alter table public.freight_requests add column if not exists observacoes_necessidade text;
alter table public.freight_requests add column if not exists empresa_remetente text;
alter table public.freight_requests add column if not exists endereco_origem text;
alter table public.freight_requests add column if not exists endereco_coleta_origem text;
alter table public.freight_requests add column if not exists nome_contato_origem text;
alter table public.freight_requests add column if not exists email_contato_origem text;
alter table public.freight_requests add column if not exists telefone_contato_origem text;
alter table public.freight_requests add column if not exists empresa_destinatario text;
alter table public.freight_requests add column if not exists endereco_destino text;
alter table public.freight_requests add column if not exists endereco_entrega_destino text;
alter table public.freight_requests add column if not exists nome_contato_destino text;
alter table public.freight_requests add column if not exists email_contato_destino text;
alter table public.freight_requests add column if not exists telefone_contato_destino text;
alter table public.freight_requests add column if not exists prazo_desejado date;
alter table public.freight_requests add column if not exists tipo_frete text;
alter table public.freight_requests add column if not exists modalidade_frete text;
alter table public.freight_requests add column if not exists necessita_seguro text;
alter table public.freight_requests add column if not exists observacoes_finais text;
alter table public.freight_requests add column if not exists empresa_solicitante text;
alter table public.freight_requests add column if not exists cnpj text;
alter table public.freight_requests add column if not exists telefone_solicitante text;
alter table public.freight_requests add column if not exists email_solicitante text;
alter table public.freight_requests add column if not exists responsavel_custos text;
alter table public.freight_requests add column if not exists payload_original jsonb not null default '{}'::jsonb;
alter table public.freight_requests add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.freight_requests add column if not exists updated_by uuid references auth.users(id) on delete set null;
alter table public.freight_requests add column if not exists created_by_email text;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'freight_requests'
      and column_name = 'type'
  ) then
    update public.freight_requests
    set freight_type = coalesce(nullif(freight_type, ''), type, 'nacional')
    where freight_type is null or freight_type = '';
  else
    update public.freight_requests
    set freight_type = coalesce(nullif(freight_type, ''), 'nacional')
    where freight_type is null or freight_type = '';
  end if;
end $$;

update public.freight_requests
set status = case status
  when 'pendente' then 'Pendente'
  when 'aprovado' then 'Agendado'
  when 'em_transito' then 'Em Rota'
  when 'entregue' then 'Concluído'
  when 'cancelado' then 'Cancelado'
  else coalesce(status, 'Pendente')
end;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'freight_requests_protocol_key'
      and conrelid = 'public.freight_requests'::regclass
  ) then
    alter table public.freight_requests add constraint freight_requests_protocol_key unique (protocol);
  end if;
end $$;

create table if not exists public.freight_request_volumes (
  id uuid primary key default gen_random_uuid(),
  freight_request_id uuid not null references public.freight_requests(id) on delete cascade,
  item_numero integer not null default 1,
  quantidade numeric(14, 3),
  dimensoes text,
  peso_bruto numeric(14, 3),
  tipo_embalagem text,
  created_at timestamptz not null default now()
);

create table if not exists public.freight_request_items (
  id uuid primary key default gen_random_uuid(),
  freight_request_id uuid not null references public.freight_requests(id) on delete cascade,
  item_numero integer not null default 1,
  quantidade numeric(14, 3),
  descricao text,
  serial_part_number text,
  ncm text,
  fabricante text,
  pais_origem text,
  valor_item numeric(14, 2),
  peso_unitario numeric(14, 3),
  created_at timestamptz not null default now()
);

create table if not exists public.freight_attachments (
  id uuid primary key default gen_random_uuid(),
  freight_request_id uuid not null references public.freight_requests(id) on delete cascade,
  category text not null default 'produto',
  file_name text,
  file_url text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.freight_status_history (
  id uuid primary key default gen_random_uuid(),
  freight_request_id uuid not null references public.freight_requests(id) on delete cascade,
  action text not null default 'status_change',
  previous_status text,
  new_status text,
  comment text,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.freight_master_options (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  label text not null,
  value text not null,
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category, value)
);

create table if not exists public.freight_email_logs (
  id uuid primary key default gen_random_uuid(),
  freight_request_id uuid references public.freight_requests(id) on delete cascade,
  destinatario text not null,
  cc text,
  assunto text not null,
  event_type text not null,
  status text not null,
  provider text not null default 'resend',
  provider_id text,
  erro text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_freight_requests_type_status on public.freight_requests(freight_type, status);
create index if not exists idx_freight_requests_protocol on public.freight_requests(protocol);
create index if not exists idx_freight_requests_created_at on public.freight_requests(created_at desc);
create index if not exists idx_freight_requests_motorista on public.freight_requests(motorista);
create index if not exists idx_freight_requests_setor on public.freight_requests(setor);
create index if not exists idx_freight_requests_projeto on public.freight_requests(projeto);
create index if not exists idx_freight_request_volumes_request on public.freight_request_volumes(freight_request_id);
create index if not exists idx_freight_request_items_request on public.freight_request_items(freight_request_id);
create index if not exists idx_freight_attachments_request on public.freight_attachments(freight_request_id);
create index if not exists idx_freight_status_history_request on public.freight_status_history(freight_request_id);
create index if not exists idx_freight_master_options_category on public.freight_master_options(category, active);
create index if not exists idx_freight_email_logs_request on public.freight_email_logs(freight_request_id);

create or replace function public.freight_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_freight_requests on public.freight_requests;
create trigger set_updated_at_freight_requests
before update on public.freight_requests
for each row execute function public.freight_set_updated_at();

drop trigger if exists set_updated_at_freight_master_options on public.freight_master_options;
create trigger set_updated_at_freight_master_options
before update on public.freight_master_options
for each row execute function public.freight_set_updated_at();

insert into public.freight_master_options (category, label, value, sort_order)
values
  ('status_nacional', 'Pendente', 'Pendente', 10),
  ('status_nacional', 'Agendado', 'Agendado', 20),
  ('status_nacional', 'Em Rota', 'Em Rota', 30),
  ('status_nacional', 'Concluído', 'Concluído', 40),
  ('status_internacional', 'Pendente', 'Pendente', 10),
  ('status_internacional', 'Em cotação', 'Em cotação', 20),
  ('status_internacional', 'Aguardando coleta', 'Aguardando coleta', 30),
  ('status_internacional', 'Em trânsito', 'Em trânsito', 40),
  ('status_internacional', 'Desembaraço', 'Desembaraço', 50),
  ('status_internacional', 'Concluído', 'Concluído', 60),
  ('status_internacional', 'Cancelado', 'Cancelado', 70),
  ('tipo_frete_internacional', 'Rodoviário', 'Rodoviário', 10),
  ('tipo_frete_internacional', 'Aéreo', 'Aéreo', 20),
  ('tipo_frete_internacional', 'Marítimo', 'Marítimo', 30),
  ('modalidade_frete', 'CIF', 'CIF', 10),
  ('modalidade_frete', 'EXW', 'EXW', 20),
  ('tipo_embalagem', 'Palete', 'Palete', 10),
  ('tipo_embalagem', 'Caixa', 'Caixa', 20)
on conflict (category, value) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'freight-attachments',
  'freight-attachments',
  true,
  20971520,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/pdf',
    'text/csv',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.freight_requests enable row level security;
alter table public.freight_request_volumes enable row level security;
alter table public.freight_request_items enable row level security;
alter table public.freight_attachments enable row level security;
alter table public.freight_status_history enable row level security;
alter table public.freight_master_options enable row level security;
alter table public.freight_email_logs enable row level security;

grant select, insert, update, delete on table
  public.freight_requests,
  public.freight_request_volumes,
  public.freight_request_items,
  public.freight_attachments,
  public.freight_status_history,
  public.freight_master_options,
  public.freight_email_logs
to authenticated;

grant select, insert, update, delete on table
  public.freight_requests,
  public.freight_request_volumes,
  public.freight_request_items,
  public.freight_attachments,
  public.freight_status_history,
  public.freight_master_options,
  public.freight_email_logs
to service_role;

grant usage, select on sequence public.freight_requests_protocol_seq to authenticated;
grant usage, select on sequence public.freight_requests_protocol_seq to service_role;

drop policy if exists "freight_requests_authenticated_read" on public.freight_requests;
create policy "freight_requests_authenticated_read"
on public.freight_requests for select to authenticated using (true);

drop policy if exists "freight_requests_authenticated_write" on public.freight_requests;
create policy "freight_requests_authenticated_write"
on public.freight_requests for all to authenticated using (true) with check (true);

drop policy if exists "freight_request_volumes_authenticated_read" on public.freight_request_volumes;
create policy "freight_request_volumes_authenticated_read"
on public.freight_request_volumes for select to authenticated using (true);

drop policy if exists "freight_request_volumes_authenticated_write" on public.freight_request_volumes;
create policy "freight_request_volumes_authenticated_write"
on public.freight_request_volumes for all to authenticated using (true) with check (true);

drop policy if exists "freight_request_items_authenticated_read" on public.freight_request_items;
create policy "freight_request_items_authenticated_read"
on public.freight_request_items for select to authenticated using (true);

drop policy if exists "freight_request_items_authenticated_write" on public.freight_request_items;
create policy "freight_request_items_authenticated_write"
on public.freight_request_items for all to authenticated using (true) with check (true);

drop policy if exists "freight_attachments_authenticated_read" on public.freight_attachments;
create policy "freight_attachments_authenticated_read"
on public.freight_attachments for select to authenticated using (true);

drop policy if exists "freight_attachments_authenticated_write" on public.freight_attachments;
create policy "freight_attachments_authenticated_write"
on public.freight_attachments for all to authenticated using (true) with check (true);

drop policy if exists "freight_status_history_authenticated_read" on public.freight_status_history;
create policy "freight_status_history_authenticated_read"
on public.freight_status_history for select to authenticated using (true);

drop policy if exists "freight_status_history_authenticated_write" on public.freight_status_history;
create policy "freight_status_history_authenticated_write"
on public.freight_status_history for insert to authenticated with check (true);

drop policy if exists "freight_master_options_authenticated_read" on public.freight_master_options;
create policy "freight_master_options_authenticated_read"
on public.freight_master_options for select to authenticated using (true);

drop policy if exists "freight_master_options_authenticated_write" on public.freight_master_options;
create policy "freight_master_options_authenticated_write"
on public.freight_master_options for all to authenticated using (true) with check (true);

drop policy if exists "freight_email_logs_authenticated_read" on public.freight_email_logs;
create policy "freight_email_logs_authenticated_read"
on public.freight_email_logs for select to authenticated using (true);

drop policy if exists "freight_email_logs_authenticated_write" on public.freight_email_logs;
create policy "freight_email_logs_authenticated_write"
on public.freight_email_logs for insert to authenticated with check (true);

drop policy if exists "freight_storage_authenticated_read" on storage.objects;
create policy "freight_storage_authenticated_read"
on storage.objects for select to authenticated
using (bucket_id = 'freight-attachments');

drop policy if exists "freight_storage_authenticated_insert" on storage.objects;
create policy "freight_storage_authenticated_insert"
on storage.objects for insert to authenticated
with check (bucket_id = 'freight-attachments');

drop policy if exists "freight_storage_authenticated_update" on storage.objects;
create policy "freight_storage_authenticated_update"
on storage.objects for update to authenticated
using (bucket_id = 'freight-attachments')
with check (bucket_id = 'freight-attachments');

drop policy if exists "freight_storage_authenticated_delete" on storage.objects;
create policy "freight_storage_authenticated_delete"
on storage.objects for delete to authenticated
using (bucket_id = 'freight-attachments');

comment on table public.freight_requests is 'Solicitacoes de frete nacional e internacional internalizadas no ConectaCup';
comment on table public.freight_status_history is 'Historico/auditoria de alteracoes de status e atendimento de frete';
comment on table public.freight_master_options is 'Opcoes operacionais do modulo de frete, como motoristas, veiculos e enderecos recorrentes';
